source 'https://rubygems.org'

gem 'colorize'
gem 'cucumber'
gem 'cuke_modeler'
gem 'httparty'
gem 'parallel_tests'
gem 'pry'
gem 'rake'
gem 'report_builder'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-checkstyle_formatter'
gem 'yaml'
