name: Healthcheck

on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  run_tests:
    uses: jhonata-santos/reusable-workflow/.github/workflows/ruby-api-tests.yml@master
  